# Generated by Django 3.2.4 on 2021-06-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210630_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuest',
            options={'ordering': ['id'], 'verbose_name': 'encuesta', 'verbose_name_plural': 'encuestas'},
        ),
    ]
